import type { CategoryInfo, Dish } from "./types";

/**
 * Mock menu for Olea. Images are free Unsplash photos referenced by their CDN
 * id; the UI optimises them and falls back to a generated visual if one ever
 * fails to load. Real photography can replace these through the API later.
 */
const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=70`;

export const categories: CategoryInfo[] = [
  {
    id: "starters",
    label: "Starters",
    description: "Small plates and mezze to open the table.",
  },
  {
    id: "mains",
    label: "Mains",
    description: "Wood-fired and slow-cooked plates from the heart of the kitchen.",
  },
  {
    id: "seafood",
    label: "From the Sea",
    description: "The day's catch, treated simply and with respect.",
  },
  {
    id: "desserts",
    label: "Desserts",
    description: "Honey, citrus, and almond — the sweet side of the coast.",
  },
  {
    id: "drinks",
    label: "Drinks",
    description: "Coastal wines, infusions, and house ferments.",
  },
];

export const dishes: Dish[] = [
  // --- Starters ---
  {
    id: "whipped-feta",
    name: "Whipped Feta & Honey",
    image: img("1559561853-08451507cbe7"),
    description:
      "Aegean feta whipped silky with olive oil, thyme honey, and toasted sesame.",
    price: 11,
    priceTier: 1,
    category: "starters",
    dietaryTags: ["vegetarian", "gluten-free", "nut-free"],
    spiceLevel: 0,
    moods: ["light", "comforting"],
    occasions: ["casual", "romantic", "family"],
    ingredients: ["feta", "thyme honey", "olive oil", "sesame"],
    featured: true,
  },
  {
    id: "charred-octopus-starter",
    name: "Charred Octopus",
    image: img("1626232441076-a2a5ada2256a"),
    description:
      "Slow-braised then grilled octopus with smoked paprika, capers, and lemon.",
    price: 16,
    priceTier: 2,
    category: "starters",
    dietaryTags: ["pescatarian", "gluten-free", "dairy-free", "contains-seafood"],
    spiceLevel: 1,
    moods: ["adventurous", "fresh"],
    occasions: ["romantic", "celebration"],
    ingredients: ["octopus", "smoked paprika", "capers", "lemon"],
  },
  {
    id: "muhammara",
    name: "Muhammara",
    image: img("1692302756206-3dd7506cb8f0"),
    description:
      "Roasted red pepper and walnut dip with pomegranate molasses and warm flatbread.",
    price: 10,
    priceTier: 1,
    category: "starters",
    dietaryTags: ["vegan", "dairy-free"],
    spiceLevel: 2,
    moods: ["adventurous", "hearty"],
    occasions: ["casual", "family"],
    ingredients: ["red pepper", "walnut", "pomegranate molasses", "flatbread"],
  },
  {
    id: "dolma",
    name: "Vine Leaf Dolma",
    image: img("1636141186543-476c0defe0f0"),
    description:
      "Vine leaves rolled with herbed rice, pine nuts, and currants, served chilled.",
    price: 9,
    priceTier: 1,
    category: "starters",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    spiceLevel: 0,
    moods: ["light", "fresh"],
    occasions: ["solo", "casual", "family"],
    ingredients: ["vine leaves", "rice", "pine nuts", "currants", "mint"],
  },
  {
    id: "halloumi-skewer",
    name: "Grilled Halloumi Skewer",
    image: img("1633857471930-bfa8d0be5e4a"),
    description:
      "Charred halloumi with cherry tomatoes, oregano, and a drizzle of carob syrup.",
    price: 12,
    priceTier: 1,
    category: "starters",
    dietaryTags: ["vegetarian", "gluten-free", "nut-free"],
    spiceLevel: 0,
    moods: ["comforting", "indulgent"],
    occasions: ["casual", "family"],
    ingredients: ["halloumi", "cherry tomato", "oregano", "carob syrup"],
  },

  // --- Mains ---
  {
    id: "lamb-tagine",
    name: "Slow Lamb Tagine",
    image: img("1773209927906-8a4187066b41"),
    description:
      "Lamb shoulder braised with apricots, cinnamon, and almonds over saffron couscous.",
    price: 27,
    priceTier: 3,
    category: "mains",
    dietaryTags: ["dairy-free", "contains-meat"],
    spiceLevel: 2,
    moods: ["hearty", "comforting", "indulgent"],
    occasions: ["celebration", "family", "romantic"],
    ingredients: ["lamb", "apricot", "cinnamon", "almond", "couscous"],
    featured: true,
  },
  {
    id: "eggplant-imam",
    name: "İmam Bayıldı",
    image: img("1587095485590-427d757332ff"),
    description:
      "Whole braised eggplant stuffed with tomato, onion, and garlic in olive oil.",
    price: 18,
    priceTier: 2,
    category: "mains",
    dietaryTags: ["vegan", "gluten-free", "dairy-free", "nut-free"],
    spiceLevel: 1,
    moods: ["hearty", "comforting"],
    occasions: ["family", "casual"],
    ingredients: ["eggplant", "tomato", "onion", "garlic", "olive oil"],
  },
  {
    id: "chicken-souvlaki",
    name: "Lemon Chicken Souvlaki",
    image: img("1604908176997-125f25cc6f3d"),
    description:
      "Charcoal-grilled chicken skewers marinated in lemon, garlic, and oregano.",
    price: 21,
    priceTier: 2,
    category: "mains",
    dietaryTags: ["gluten-free", "dairy-free", "nut-free", "contains-meat"],
    spiceLevel: 1,
    moods: ["fresh", "hearty"],
    occasions: ["casual", "family", "solo"],
    ingredients: ["chicken", "lemon", "garlic", "oregano"],
  },
  {
    id: "harissa-cauliflower",
    name: "Harissa Roasted Cauliflower",
    image: img("1510629954389-c1e0da47d414"),
    description:
      "Whole cauliflower roasted in harissa with tahini, dukkah, and herb oil.",
    price: 19,
    priceTier: 2,
    category: "mains",
    dietaryTags: ["vegan", "gluten-free", "dairy-free"],
    spiceLevel: 3,
    moods: ["adventurous", "hearty"],
    occasions: ["casual", "celebration"],
    ingredients: ["cauliflower", "harissa", "tahini", "dukkah"],
    featured: true,
  },
  {
    id: "beef-kofta",
    name: "Spiced Beef Köfte",
    image: img("1532636875304-0c89119d9b4d"),
    description:
      "Charcoal köfte with smoked chili, grilled peppers, and burnt-onion yogurt.",
    price: 23,
    priceTier: 2,
    category: "mains",
    dietaryTags: ["gluten-free", "nut-free", "contains-meat"],
    spiceLevel: 2,
    moods: ["hearty", "indulgent"],
    occasions: ["family", "casual"],
    ingredients: ["beef", "smoked chili", "pepper", "yogurt"],
  },
  {
    id: "saffron-risotto",
    name: "Saffron & Lemon Risotto",
    image: img("1476124369491-e7addf5db371"),
    description:
      "Carnaroli rice with saffron, preserved lemon, and aged pecorino.",
    price: 20,
    priceTier: 2,
    category: "mains",
    dietaryTags: ["vegetarian", "gluten-free", "nut-free"],
    spiceLevel: 0,
    moods: ["comforting", "indulgent"],
    occasions: ["romantic", "solo"],
    ingredients: ["carnaroli rice", "saffron", "preserved lemon", "pecorino"],
  },

  // --- From the Sea ---
  {
    id: "grilled-sea-bass",
    name: "Whole Grilled Sea Bass",
    image: img("1665401015549-712c0dc5ef85"),
    description:
      "Line-caught sea bass over charcoal with fennel, lemon, and caper berries.",
    price: 29,
    priceTier: 3,
    category: "seafood",
    dietaryTags: ["pescatarian", "gluten-free", "dairy-free", "nut-free", "contains-seafood"],
    spiceLevel: 0,
    moods: ["light", "fresh"],
    occasions: ["romantic", "celebration"],
    ingredients: ["sea bass", "fennel", "lemon", "caper berries"],
    featured: true,
  },
  {
    id: "garlic-prawns",
    name: "Sizzling Garlic Prawns",
    image: img("1625943553852-781c6dd46faa"),
    description:
      "Prawns seared in chili, garlic, and olive oil with grilled sourdough.",
    price: 22,
    priceTier: 2,
    category: "seafood",
    dietaryTags: ["pescatarian", "dairy-free", "contains-seafood"],
    spiceLevel: 2,
    moods: ["adventurous", "indulgent"],
    occasions: ["casual", "romantic"],
    ingredients: ["prawns", "chili", "garlic", "sourdough"],
  },
  {
    id: "calamari",
    name: "Crispy Calamari",
    image: img("1675377668870-baf9b35763f9"),
    description:
      "Lightly fried calamari with smoked aioli and a squeeze of lemon.",
    price: 17,
    priceTier: 2,
    category: "seafood",
    dietaryTags: ["pescatarian", "contains-seafood"],
    spiceLevel: 0,
    moods: ["comforting", "indulgent"],
    occasions: ["casual", "family"],
    ingredients: ["calamari", "aioli", "lemon"],
  },
  {
    id: "seafood-stew",
    name: "Coastal Seafood Stew",
    image: img("1761530291482-c3ed81a7fc3a"),
    description:
      "Mussels, clams, and white fish in a saffron-tomato broth with herbs.",
    price: 26,
    priceTier: 3,
    category: "seafood",
    dietaryTags: ["pescatarian", "gluten-free", "dairy-free", "contains-seafood"],
    spiceLevel: 1,
    moods: ["hearty", "comforting"],
    occasions: ["family", "celebration"],
    ingredients: ["mussels", "clams", "white fish", "saffron", "tomato"],
  },

  // --- Desserts ---
  {
    id: "baklava",
    name: "Pistachio Baklava",
    image: img("1598110750624-207050c4f28c"),
    description:
      "Layered filo with Antep pistachios and orange-blossom syrup.",
    price: 9,
    priceTier: 1,
    category: "desserts",
    dietaryTags: ["vegetarian"],
    spiceLevel: 0,
    moods: ["indulgent", "comforting"],
    occasions: ["celebration", "family"],
    ingredients: ["filo", "pistachio", "orange blossom", "butter"],
    featured: true,
  },
  {
    id: "citrus-olive-cake",
    name: "Olive Oil & Citrus Cake",
    image: img("1702165640704-500de9043903"),
    description:
      "Moist olive oil cake with orange, almond, and a spoon of mascarpone.",
    price: 8,
    priceTier: 1,
    category: "desserts",
    dietaryTags: ["vegetarian"],
    spiceLevel: 0,
    moods: ["light", "comforting"],
    occasions: ["casual", "romantic"],
    ingredients: ["olive oil", "orange", "almond", "mascarpone"],
  },
  {
    id: "yogurt-honey",
    name: "Strained Yogurt & Honey",
    image: img("1763825613390-287a9db0803d"),
    description:
      "Thick yogurt with walnut, thyme honey, and roasted figs.",
    price: 7,
    priceTier: 1,
    category: "desserts",
    dietaryTags: ["vegetarian", "gluten-free"],
    spiceLevel: 0,
    moods: ["light", "fresh"],
    occasions: ["solo", "casual"],
    ingredients: ["yogurt", "walnut", "thyme honey", "fig"],
  },
  {
    id: "lemon-sorbet",
    name: "Amalfi Lemon Sorbet",
    image: img("1724805053558-aea1220afbfa"),
    description:
      "Bright lemon sorbet with a touch of basil and sea salt.",
    price: 6,
    priceTier: 1,
    category: "desserts",
    dietaryTags: ["vegan", "gluten-free", "dairy-free", "nut-free"],
    spiceLevel: 0,
    moods: ["light", "fresh"],
    occasions: ["solo", "casual"],
    ingredients: ["lemon", "basil", "sea salt"],
  },

  // --- Drinks ---
  {
    id: "house-white",
    name: "Coastal House White",
    image: img("1585553616435-2dc0a54e271d"),
    description:
      "Crisp unoaked white with notes of green apple and sea breeze.",
    price: 8,
    priceTier: 1,
    category: "drinks",
    dietaryTags: ["vegan", "gluten-free", "dairy-free", "nut-free"],
    spiceLevel: 0,
    moods: ["light", "fresh"],
    occasions: ["romantic", "celebration", "casual"],
    ingredients: ["white wine"],
  },
  {
    id: "pomegranate-spritz",
    name: "Pomegranate Spritz",
    image: img("1589378938275-947b7adf8665"),
    description:
      "Sparkling spritz with pomegranate, citrus, and fresh mint.",
    price: 9,
    priceTier: 1,
    category: "drinks",
    dietaryTags: ["vegan", "gluten-free", "dairy-free", "nut-free"],
    spiceLevel: 0,
    moods: ["fresh", "adventurous"],
    occasions: ["celebration", "casual"],
    ingredients: ["pomegranate", "citrus", "mint", "soda"],
    featured: true,
  },
  {
    id: "mint-tea",
    name: "Fresh Mint Tea",
    image: img("1567708415681-d1d249e182eb"),
    description:
      "Steeped green tea with handfuls of fresh mint and a touch of honey.",
    price: 5,
    priceTier: 1,
    category: "drinks",
    dietaryTags: ["vegetarian", "gluten-free", "nut-free"],
    spiceLevel: 0,
    moods: ["light", "comforting"],
    occasions: ["solo", "family", "casual"],
    ingredients: ["green tea", "mint", "honey"],
  },
];
